apiVersion: apps/v1
kind: Deployment
metadata:
  name: mo-ux-deployment
  namespace: middleoffice
  labels:
    app: mo-ux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mo-ux
  template:
    metadata:
      labels:
        app: mo-ux
    spec:
      containers:
      - name: mo-uxrequest
        image: jpgouigoux/mo-uxrequest
        env:
        - name: PORT
          value: "81"
        - name: BASE_URL
          value: "http://portal.microservice.k8s.lab"         
        ports:
        - containerPort: 81
          name: http81
          
      - name: mo-portal
        image: jpgouigoux/mo-portal:0.1
        ports:
        - containerPort: 80
          name: http
        env:
        - name: BASE_URL
          value: "http://portal.microservice.k8s.lab"
          
      - name: mo-uxrequest-vote
        image: jpgouigoux/mo-uxrequest-vote
        env:
        - name: PORT
          value: "82"
        - name: BASE_URL
          value: "http://portal.microservice.k8s.lab"          
        ports:
        - containerPort: 82
          name: http82
          
      - name: mo-uxrequests-tobevoted
        image: jpgouigoux/mo-uxrequests-tobevoted
        env:
        - name: PORT
          value: "83"
        - name: BASE_URL
          value: "http://mo-api-service.middleoffice.svc.cluster.local:81"          
        ports:
        - containerPort: 83
          name: http83
          
      - name: mo-uxrequesttype
        image: jpgouigoux/mo-uxrequesttype
        env:
        - name: PORT
          value: "84" 
        - name: BASE_URL
          value: "http://portal.microservice.k8s.lab"
        ports:
        - containerPort: 84
          name: http84
