apiVersion: apps/v1
kind: Deployment
metadata:
  name: mo-ux-deployment
  labels:
    app: mo-ux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mo-ux
  template:
    metadata:
      labels:
        app: mo-ux
    spec:
      containers:
      - name: mo-uxrequest
        image: jpgouigoux/mo-uxrequest
        env:
        - name: PORT
          value: "81"
        ports:
        - containerPort: 81
          name: http81
      - name: mo-portal
        image: jpgouigoux/mo-portal
        ports:
        - containerPort: 80
          name: http