apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-service-nodeport
  namespace: middleoffice
spec:
  ports:
  - nodePort: 30017
    name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  type: NodePort
  selector:
    app: mongo