apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastic
  name: elastic-service
  namespace: middleoffice
spec:
  ports:
  - name: elastic
    port: 9200
    protocol: TCP
    targetPort: 9200
  type: ClusterIP
  selector:
    app: elastic